version: "3.5"
services:

  notebook:
    build: ../../jupyter
    container_name: notebook
    ports:
      - 8888:8888
    volumes:
      - ../../data:/data
      - ../../notebooks:/home/jovyan/work

  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"

