name: "Check notebooks"
on:
  push:
    branches:
      # - 'master'
  pull_request:

jobs:
  check-notebooks:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build container
        run: docker-compose pull && docker-compose build && docker-compose up -d

      - name: Wait until Jupyter container is up
        run: |
          while ! nc -z localhost 8888; do
            sleep 1
          done

      - name: Wait until lakeFS container is properly up
        run: |
          timeout=$((SECONDS + 300))  # Set timeout to 5 minutes from now
          while [ $SECONDS -lt $timeout ]; do
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/_health)
            echo $?
            echo output

            # Check if the response is a success code
            if [[ $response -ge 200 && $response -lt 300 ]]; then
              echo "\o/ lakeFS is reachable from host"
              exit 0
            else
              echo "Failed with response code $response"
              
              sleep 5
            fi
          done

          if [ $SECONDS -ge $timeout ]; then
              echo "Timeout reached, command did not return 'alive' within 5 minutes"
              exit 1
          fi

      - name: Check lakeFS connection locally
        run: |
          curl http://localhost:8000/_health 2>&1

      - name: Wait until lakeFS container is up and ready and reachable from Jupyter
        run: |
          timeout=$((SECONDS + 300))  # Set timeout to 5 minutes from now
          while [ $SECONDS -lt $timeout ]; do
              output=$(docker exec $(docker ps -q --filter expose=8888) wget -q -O - http://lakefs:8000/_health 2>&1)
              echo $?
              echo output
              if [[ $output == alive* ]]; then
                  echo "Command returned: $output"
                  break
              fi
              sleep 5  # Wait for 1 second before trying again
          done

          if [ $SECONDS -ge $timeout ]; then
              echo "Timeout reached, command did not return 'alive' within 5 minutes"
              exit 1
          fi

      - name: Container status
        run: |
          docker ps -a

      - name: Container log
        run: |
          docker logs $(docker ps -q --filter expose=8000)

      - name: Run notebooks
        run: |
          docker exec $(docker ps -q --filter expose=8888) papermill "/home/jovyan/dev-test.ipynb"

          # cd notebooks && \
          # find . -name "*.ipynb" | \
          # grep -vFf ../.github/workflows/notebooks_to_exclude.txt | \
          # grep -v .ipynb_checkpoints | \
          # xargs -I {} echo {}
#          xargs -I {} docker exec $(docker ps -q --filter expose=8888) papermill "/home/jovyan/{}"
