name: "Check notebooks"
on:
  push:
    branches:
      # - 'master'
  pull_request:

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build container
        run: docker-compose pull && docker-compose build && docker-compose up -d

      - name: Wait until Jupyter container is up
        run: |
          while ! nc -z localhost 8888; do
            sleep 1
          done

      - name: Wait until lakeFS container is up
        run: |
          while ! nc -z localhost 8000; do
            sleep 1
          done

      - name: Run notebooks
        run: |
          cd notebooks && \
          find . -name "*.ipynb" | \
          grep -vFf ../.github/workflows/notebooks_to_exclude.txt | \
          grep -v .ipynb_checkpoints | \
          xargs -I {} echo {}
#          xargs -I {} docker exec $(docker ps -q --filter expose=8888) papermill "/home/jovyan/{}"
