name: "Check notebooks"
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '01_standalone_examples/**'
  pull_request:
    paths-ignore:
      - '01_standalone_examples/**'

jobs:
  check-notebooks:
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build container
        run: docker compose up --build --pull always -d

      - name: Wait until Jupyter container is up
        run: |
          while ! nc -z localhost 8888; do
            sleep 1
          done

      - name: Wait until lakeFS container is properly up
        run: |
          while ! curl -s http://localhost:8000/_health; do
            sleep 1
          done

      - name: Run all notebooks other than those excluded
        working-directory: 00_notebooks
        run: |
          mkdir -p papermill-out
          ls -lR .
          find . -name "*.ipynb" | \
            grep -vFf <(grep -v -e '^#' -e '^$' ../.github/workflows/notebooks_to_exclude.txt) | \
            xargs -I {} docker exec $(docker ps -q --filter expose=8888) \
              papermill -cwd /home/jovyan/notebooks/ \
                        "/home/jovyan/notebooks/{}" \
                        "/home/jovyan/notebooks/papermill-out/{}" \
                        2> papermill-out/papermill.err \
                        1> papermill-out/papermill.out || true

      - name: Check for any failed notebooks
        working-directory: 00_notebooks
        run: |
          mkdir -p papermill-out/failed
          for file in $(grep -r -l "papermill-error-cell-tag" papermill-out); do
            mv "$file" papermill-out/failed
            echo "😱 Notebook failed: $file"
          done

          # Set the exit code based on whether we detected any failures
          if [ "$(ls -A papermill-out/failed)" ]; then
            mv papermill-out/papermill.err papermill-out/failed
            mv papermill-out/papermill.out papermill-out/failed
            echo ""
            echo "🚨👆🏻👆🏻 Failing notebooks found 👆🏻👆🏻🚨"
            exit 1
          else
            echo "No failures found"
          fi

      - name: Store any failing test artifacts
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: Failed notebooks
          path: |
            00_notebooks/papermill-out/failed